name: S3 Deployment pipeline
run-name: ${{github.actor}} is deploying new version to S3
on: 
  pull_request:
    branches:
      - main
      - 'release/**'
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      env:
        AWS_REGION: ${{secrets.AWS_REGION}}
        AWS_OIDC_IAM_ROLE_ARN: ${{secrets.AWS_OIDC_IAM_ROLE_ARN}}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "$AWS_REGION"
          role-to-assume: "$AWS_OIDC_IAM_ROLE_ARN"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checking Terraform configuration
        runs: terraform init

      - name: Validate Terraform syntax
        runs: terraform validate

      - name: Execute Terraform
        runs: terraform apply -auto-approve
      
        
    


