name: S3 Deployment pipeline
run-name: ${{github.actor}} is deploying new version to S3
on: 
  pull_request:
    branches:
      - main
      - 'release/**'
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_OIDC_IAM_ROLE_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}
    
    steps:

      - name: Deploy to AWS region
        run: echo "$AWS_REGION"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "$AWS_REGION"
          role-to-assume: "$AWS_OIDC_IAM_ROLE_ARN"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checking Terraform configuration
        run: terraform init
        working-directory: iac

      - name: Validate Terraform syntax
        run: terraform validate
        working-directory: iac

      - name: Execute Terraform
        run: terraform apply -auto-approve
        working-directory: iac
      
          
    


